version: '2'

services:
  redis:
    image: redis:5.0.4-alpine
    volumes:
    - ${PWD}/tmp/data:/data
    ports:
    - "6379:6379"
    container_name: "redis-mosq"

  mosquitto:
    #build: .
    image: farmshelf/mqtt
    volumes:
    - ${PWD}/auth-plugin.conf:/etc/mosquitto.d/auth-plugin.conf
    - ~/.mosquittopass:/.mosquittopass
    ports:
    - "1883:1883"
    - "9883:9883"
    environment:
    - DOMAIN=example.local
    - PORT=8080
    #depends_on:
    #- redis
    labels:
    - "local.example.description=Mosquitto v1.6.4 MQTT server"
